# Generated by Django 3.0.8 on 2021-04-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=10)),
                ('c_desc', models.CharField(max_length=100)),
                ('c_title', models.CharField(max_length=20)),
            ],
        ),
    ]
