# Generated by Django 3.0.8 on 2021-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_image',
            field=models.ImageField(default='', upload_to='c_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_title',
            field=models.CharField(max_length=50),
        ),
    ]
