# Generated by Django 3.0.8 on 2021-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0003_auto_20210412_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_title', models.CharField(max_length=50)),
                ('v_cat', models.CharField(max_length=10)),
                ('v_desc', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=50)),
                ('v_image', models.ImageField(default='', upload_to='v_images/')),
            ],
        ),
    ]
