# Generated by Django 4.0.1 on 2022-03-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='v_desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='v_title',
            field=models.CharField(max_length=100),
        ),
    ]
